# Generated by Django 5.2.1 on 2025-06-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('MOTIVACIONAL', 'Motivacional'), ('LIFESTYLE', 'Lifestyle'), ('ESTRATÉGIA', 'Estratégia'), ('FINANÇAS', 'Finanças')], default='', max_length=100),
        ),
    ]
