# Generated by Django 5.2.1 on 2025-06-26 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_livro_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_adicao_livro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
