# Generated by Django 5.2.1 on 2025-07-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_livro_data_adicao_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
